Adding adversarial simulator samples
Azure-Samples/azureai-samples pull request #70
Opened 2024-03-21 02:09 UTC by nagkumar91

# Description

# Checklist

- [ ] I have read the [contribution guidelines](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md)
- [ ] I have coordinated with the docs team (mldocs@microsoft.com) if this PR deletes files or changes any file names or file extensions.
- [ ] This notebook or file is added to the [CODEOWNERS](https://github.com/Azure-Samples/azureai-samples/blob/main/.github/CODEOWNERS) file, pointing to the author or the author's team.

2024-03-26 15:12 UTC, minthigpen reviewed
Can you please add a readme to the scenarios/generate-synthetic-data folder with a description of the samples and what they help users do? happy to review, but just a table would be great.

2024-03-27 21:08 UTC, qusongms commented on scenarios/generate-synthetic-data/adversarial-simulator/conversation/simulate_and_evaluate_conversation.ipynb
> +    "result = evaluate(\n",
the output is generated by to_json_lines() -- assume it's in chat protocol. 
In evaluate function, task_type should be "chat".
The supported metricf list is ["hate_unfairness", "violence", "self_harm", "sexual", "gpt_coherence", "gpt_fluency", "gpt_groundedness", "gpt_relevance", "gpt_retrieval_score"], the last 3 metrics require context (documents) in assisitant role, therefore they may fail if there's no context and no "documents" under "context".

2024-03-27 21:08 UTC, qusongms commented on scenarios/generate-synthetic-data/adversarial-simulator/rewrite/simulate_and_evaluate_rewrite.ipynb
> +    "result = evaluate(\n",
the output is generated by to_jsons_lines() -- therefore it's expected to be in chat format. 
In evaluation fucntion, task_type should be "chat". 
"gpt_similarity" is not supported in chat scenario.

The supported metricf list for chat is ["hate_unfairness", "violence", "self_harm", "sexual", "gpt_coherence", "gpt_fluency", "gpt_groundedness", "gpt_relevance", "gpt_retrieval_score"], the last 3 metrics require context (documents) in assisitant role, therefore they may fail if there's no context and no "documents" under "context".

2024-03-27 21:08 UTC, qusongms commented on scenarios/generate-synthetic-data/adversarial-simulator/search/simulate_and_evaluate_search.ipynb
> +    "result = evaluate(\n",
similar to previous review, set task_type to "chat" in evaluation function, and update metrics_list.

2024-03-27 21:08 UTC, qusongms commented on scenarios/generate-synthetic-data/adversarial-simulator/summarization/simulate_and_evaluate_summarization.ipynb
> +    "    evaluation_name=eval_name,\n",
similar to previous review, set task_type to "chat" in evaluation function, and update metrics_list.

2024-03-27 21:08 UTC, qusongms commented on scenarios/generate-synthetic-data/non-adversarial-simulator/conversation/simulate_and_evaluate_conversation.ipynb
> +    "result = evaluate(\n",
similar to previous review, set task_type to "chat" in evaluation function.

2024-03-27 21:08 UTC, qusongms commented on scenarios/generate-synthetic-data/non-adversarial-simulator/summarization/simulate_and_evaluate_summarization.ipynb
> +    "result = evaluate(\n",
similar to previous review, set task_type to "chat" in evaluation function, and update metrics_list.

2024-03-27 21:38 UTC, kdestin requested changes

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/promptflow/simulate_against_promptflow.py
> +# pylint: skip-file
Unneeded pylint directive

```suggestion
```

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/rag/simulate_and_evaluate_rag.py
> +# pylint: skip-file
Unneeded pylint directive

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/content-generation/simulate_and_evaluate_grounded_content_generator.ipynb
I don't know that I have any firm opinions here, but I still wanted to highlight this.

`simulate_and_evaluate_grounded_content_generator.ipynb` and `simulate_and_evaluate_ungrounded_content_generator.ipynb` differ by a total of 4 lines:

```diff

--- simulate_and_evaluate_grounded_content_generator.ipynb  2024-03-27 17:12:48.974059
+++ simulate_and_evaluate_ungrounded_content_generation.ipynb  2024-03-27 17:12:48.898060
## modified /cells/0/source:
-  # Adversarial Simulator for grounded content generation
+  # Adversarial Simulator for Summarization

## modified /cells/3/source:
@@ -4,4 +4,4 @@ client = AIClient(
 )
 
 simulator = Simulator.from_fn(fn=async_oai_chat_completion_fn, ai_client=client, model="gpt-4", max_tokens=300)
-adv_template = Simulator.get_template("adv_content_gen_grounded")

+adv_template = Simulator.get_template("adv_content_gen_ungrounded")


## modified /cells/5/source:
@@ -2,5 +2,5 @@ outputs = await simulator.simulate_async(
     adv_template,
     max_conversation_turns=2,
     api_call_delay_sec=10,
-    max_simulation_results=5,
+    max_simulation_results=10,
 )


## modified /cells/9/source:
@@ -1,4 +1,4 @@
-eval_name = "conv-oai-grounded-content-generation-eval"
+eval_name = "conv-oai-ungrounded-content-generation-eval"
 file_name = f"\{eval_name}.jsonl"
 jsonl_object = outputs.to_json_lines()
 with Path.open(file_name, "w") as f:
```


Would you say that this changeset is substantive enough to warrant maintaining 2 nearly identical samples? Would the learning outcomes be different if we kept one notebook, and noted that you can do the other case by switching templates?


---

- [ ] Doesn't follow notebook template
- [ ] Jupyter Notebook is not in its own directory
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/content-generation/simulate_and_evaluate_ungrounded_content_generation.ipynb
- [ ] Doesn't follow notebook template
- [ ] Jupyter Notebook is not in its own directory
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/conversation/simulate_and_evaluate_conversation.ipynb
- [ ] Doesn't follow notebook template
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/promptflow/simulate_against_promptflow.py
Is there a reason this sample is a loose python file instead of a Jupyter Notebook?

If there isn't, please make this sample into a Jupyter Notebook using our notebook template. 

Users that would prefer to just run a python file can still do so by:

* Using [nbconvert](https://github.com/jupyter/nbconvert)
* Using Visual Studio Code built in support for converting notebooks to Python files.

---

- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/rewrite/simulate_and_evaluate_rewrite.ipynb
- [ ] Doesn't follow notebook template
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/search/simulate_and_evaluate_search.ipynb
- [ ] Doesn't follow notebook template
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/summarization/simulate_and_evaluate_summarization.ipynb
- [ ] Doesn't follow notebook template
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/non-adversarial-simulator/conversation/simulate_and_evaluate_conversation.ipynb
- [ ] Doesn't follow notebook template
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/non-adversarial-simulator/summarization/simulate_and_evaluate_summarization.ipynb
- [ ] Doesn't follow notebook template
- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 21:38 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/rag/simulate_and_evaluate_rag.py
Is there a reason this sample is a loose python file instead of a Jupyter Notebook?

If there isn't, please make this sample into a Jupyter Notebook using our notebook template. 

Users that would prefer to just run a python file can still do so by:

* Using [nbconvert](https://github.com/jupyter/nbconvert)
* Using Visual Studio Code built in support for converting notebooks to Python files.
---

- [ ] Missing accompanying README.md that allows for discovery on learn.microsoft.com

See our [contributing guide](https://github.com/Azure-Samples/azureai-samples/blob/main/CONTRIBUTING.md#write-your-contribution) for more details.

2024-03-27 23:05 UTC, nagkumar91 commented on scenarios/generate-synthetic-data/adversarial-simulator/content-generation/simulate_and_evaluate_grounded_content_generator.ipynb
Technically all the adversarial templates are a one line change (the line with `Simulator.get_template`)
Having different files would help us use the same notebooks for end-to-tests? I don't mind removing it or keeping it.

2024-03-28 01:13 UTC, nagkumar91 commented on scenarios/generate-synthetic-data/adversarial-simulator/rag/simulate_and_evaluate_rag.py
The notebook wasn't working for some reason. So I had to switch to a python file.

2024-03-28 18:03 UTC, diondrapeck approved these changes

2024-03-28 18:25 UTC, kdestin commented on scenarios/generate-synthetic-data/adversarial-simulator/rag/simulate_and_evaluate_rag.py
Does running it as a python file work?

---

This sample is still missing a README.md for discoverability in repo and on learn.microsoft.com

2024-03-28 18:31 UTC, kdestin approved these changes

2024-03-28 18:32 UTC, nagkumar91 commented on scenarios/generate-synthetic-data/adversarial-simulator/rag/simulate_and_evaluate_rag.py
yes, it works as a python file. We'll work with customers/advocates to make sure it follows the notebook standards in the future.

2024-03-28 18:35 UTC, merged